### ISSUE TITLE
Don't work with last version of coverage (4.1b2)

### ISSUE THREAD

**Issue by rodfersou** [reinout/createcoverage#3]
``` shell
$ ./bin/coverage
Traceback (most recent call last):
  File "./bin/coverage", line 14, in <module>
    sys.exit(coverage.main())
AttributeError: 'module' object has no attribute 'main'
```

**Comment by reinout** [comment]
I can probably remove the `bin/coverage` from our setup.py. For pip, it is no problem. For buildout I'll then have to add a line of documentation to add `dependent-scripts = true` to a zc.recipe.egg.

Very busy today, so I don't know if I can do it today. Feel free to remind me next week if I haven't fixed it by then.

**Comment by rodfersou** [comment]
I didn't understand how removing the `bin/coverage` will fix something..

**Comment by rodfersou** [comment]
AFAIK we need to change `bin/coverage` to use `coverage.cmdline.main` instead of `coverage.main`, take a look here https://github.com/nedbat/coveragepy/blob/master/coverage/__main__.py#L7-L8
