### PR TITLE
Fix coverage command line utility

### LINKED ISSUE #3: Don't work with last version of coverage (4.1b2)
``` shell
$ ./bin/coverage
Traceback (most recent call last):
  File "./bin/coverage", line 14, in <module>
    sys.exit(coverage.main())
AttributeError: 'module' object has no attribute 'main'
```

### PR DESCRIPTION
**Pull request by rodfersou**
I think this will fix coverage script, but could not make sure with our buildout.. It looks like we need a release to make buildout look for these changes.

closes #3

### CODE REVIEW

**Comment by hvelarde** [comment]
a new release will be appreciated

**Comment by reinout** [comment]
I just released 1.5. Can you check if it works for you?

**Comment by hvelarde** [comment]
it works!: https://coveralls.io/github/collective/collective.behavior.featuredimage
thanks, @reinout!

**Comment by rodfersou** [comment]
nice! :beers:
